project_id = "fuxysjxwwaxhaclibblf"

[functions.get-wallet-balances]
verify_jwt = false

[functions.oracle-automation]
verify_jwt = false

[functions.get-farcaster-profiles]
verify_jwt = false

[functions.generate-share-image]
verify_jwt = false
